name: CI

on:
    pull_request:
        branches:
        - '*'
    push:
        branches:
        - master
        - main
    workflow_dispatch:

jobs:
    specs2:
        name: specs2
        runs-on: actuated
        steps:
        - uses: actions/checkout@v1
        - name: Check specs
          run: |
            ./specs.sh
